# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eee3369fd110c51041881b4e4139e551279120c29b379f3a909d88a8bcaf640aaf90185ed7a357bbe46972dad6240c3ac4b2851bbe591c39474c94b8e0bd36b1

test:
  secret_key_base: 72d43725cbb80bd1c4c737f47b0ec97b218f9567cbcbd076f76202f8bb6dd5f84de268e27be8cbdd8d414aa444047a3a3b6e32e9af7079365a1ee6363190000f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 674997c9eb4e834cfb8b7257f80d04476643c72315f9fc61ef6f27f7b2c88046a8e731b939156b350a2cf5193e5effb6f7c63dd87b6c9f961a31aa62d64c1666
